<?php

namespace App\Console\Commands;

use App\Services\Mssql\LegacyMirrorSourceService;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\Schema;

class CompareLegacySchema extends Command
{
    protected $signature = 'mssql:compare-schema
        {--output= : Optional markdown output path relative to storage/app}';

    protected $description = 'Compare legacy BPlus MSSQL tables/columns with the normalized ERP schema without writing to MSSQL.';

    /** @var array<string, string> */
    private const CORE_MAPPING = [
        'BRANCH' => 'branches',
        'WAREHOUSE' => 'warehouses',
        'WARELOCATION' => 'warehouse_locations',
        'DOCTYPE' => 'document_types',
        'DOCINFO' => 'documents',
        'SALESMAN' => 'salesmen',
        'ARFILE' => 'customers',
        'ARCONTACT' => 'customer_contacts',
        'SKUMASTER' => 'products',
        'GOODSMMASTER' => 'product_barcodes',
        'GOODSMASTER' => 'product_barcodes',
        'UOFQTY' => 'product_units',
        'TRANSTKH' => 'stock_documents',
        'TRANSTKD' => 'stock_document_items',
        'SKUMOVE' => 'stock_movements',
        'AROE' => 'customer_open_items',
        'ARDETAIL' => 'customer_ledger',
        'ACCOUNTCHART' => 'chart_of_accounts',
        'TRANPAYJ' => 'gl_journals',
        'CASHBOOK' => 'cash_books',
        'BANKACCOUNT' => 'bank_accounts',
        'BANKFILE' => 'bank_accounts',
        'MEMBER' => 'members',
    ];

    public function handle(LegacyMirrorSourceService $source): int
    {
        $legacyTables = $source->tables();
        $newTables = collect(Schema::getTables())
            ->pluck('name')
            ->filter(fn (string $name): bool => $name !== 'migrations')
            ->values()
            ->all();
        $newByLower = array_fill_keys(array_map('strtolower', $newTables), true);

        $legacyColumns = [];
        foreach ($legacyTables as $table) {
            $name = strtoupper($table['name']);
            $legacyColumns[$name] = array_map(
                fn (array $column): string => strtoupper($column['name']),
                $source->columns($table['schema'], $table['name']),
            );
        }

        $mapping = [];
        foreach ($legacyColumns as $legacy => $columns) {
            $new = self::CORE_MAPPING[$legacy] ?? null;
            if ($new === null && isset($newByLower[strtolower($legacy)])) {
                $new = strtolower($legacy);
            }

            $newColumnNames = $new !== null && in_array($new, $newTables, true)
                ? array_map('strtoupper', Schema::getColumnListing($new))
                : [];
            $shared = array_values(array_intersect($columns, $newColumnNames));

            $mapping[] = [
                'legacy' => $legacy,
                'new' => $new,
                'legacy_columns' => count($columns),
                'new_columns' => count($newColumnNames),
                'shared_columns' => count($shared),
                'coverage' => $newColumnNames === [] ? 0 : round(count($shared) / count($columns) * 100, 2),
            ];
        }

        $report = $this->renderReport($legacyTables, $newTables, $mapping);
        $output = trim((string) $this->option('output'));
        if ($output !== '') {
            $path = storage_path('app/'.ltrim($output, '/'));
            if (! is_dir(dirname($path))) {
                mkdir(dirname($path), 0775, true);
            }
            file_put_contents($path, $report);
            $this->info('Report written: '.$path);
        }

        $this->line($report);

        return self::SUCCESS;
    }

    private function renderReport(array $legacyTables, array $newTables, array $mapping): string
    {
        $mapped = collect($mapping)->filter(fn (array $row): bool => $row['new'] !== null);
        $unmapped = collect($mapping)->filter(fn (array $row): bool => $row['new'] === null);
        $legacyColumnCount = collect($mapping)->sum('legacy_columns');
        $newColumnCount = collect($mapping)->sum('new_columns');

        $lines = [
            '# Database Schema Comparison',
            '',
            '> Generated by `mssql:compare-schema`. The legacy MSSQL source is read-only; this report does not modify it.',
            '',
            '## Summary',
            '',
            '| Metric | Count |',
            '|---|---:|',
            '| Legacy MSSQL tables | '.count($legacyTables).' |',
            '| New ERP tables | '.count($newTables).' |',
            '| Legacy columns across mapped rows | '.$legacyColumnCount.' |',
            '| New columns across mapped rows | '.$newColumnCount.' |',
            '| Tables with a mapping | '.$mapped->count().' |',
            '| Legacy tables without mapping | '.$unmapped->count().' |',
            '',
            '## Interpretation',
            '',
            'The counts are not expected to be identical. The new ERP normalizes Bplus tables into business domains, so one legacy table can map to multiple new tables and some legacy columns are intentionally replaced by foreign keys, ledgers, or document lifecycle fields.',
            '',
            '## Mapping Detail',
            '',
            '| Legacy table | New table | Legacy columns | New columns | Shared names | Coverage* |',
            '|---|---|---:|---:|---:|---:|',
        ];

        foreach ($mapping as $row) {
            $lines[] = sprintf(
                '| `%s` | `%s` | %d | %d | %d | %.2f%% |',
                $row['legacy'],
                $row['new'] ?? 'UNMAPPED',
                $row['legacy_columns'],
                $row['new_columns'],
                $row['shared_columns'],
                $row['coverage'],
            );
        }

        $lines[] = '';
        $lines[] = '*Coverage is a name-overlap indicator only, not a data-quality or business-equivalence sign-off.*';

        return implode("\n", $lines);
    }
}
