@extends('layout')
@section('title','ภาษีไทยและ E-Tax - PopCentral')
@section('page-title','ศูนย์ภาษีไทยและ E-Tax')
@section('page-subtitle','จัดทำ ตรวจทาน บันทึกการยื่น ภ.พ.30/ภ.ง.ด.3/53 และติดตาม E-Tax')
@push('head')<style>[x-cloak]{display:none!important}.tax-shell{display:grid;gap:12px}.tax-panel{background:#fff;border:1px solid var(--erp-border);border-radius:7px;padding:14px}.tax-filter{display:flex;gap:9px;align-items:end;flex-wrap:wrap}.tax-tabs{display:flex;gap:5px;border-bottom:1px solid var(--erp-border);padding-bottom:8px}.tax-tab{border:0;background:var(--erp-primary-soft);color:var(--erp-muted);border-radius:6px;padding:8px 12px;font-weight:800}.tax-tab.active{background:var(--erp-primary-dark);color:#fff}.tax-note{padding:10px;border-left:3px solid var(--erp-warning-ink);background:var(--erp-warning-soft);color:var(--erp-warning-ink);font-size:11px}.tax-actions{display:flex;gap:5px;flex-wrap:wrap}.tax-actions form{display:flex;gap:5px}.tax-actions input,.tax-actions select{height:30px;font-size:11px;border:1px solid var(--erp-border);border-radius:5px;padding:0 6px}@media(max-width:640px){.tax-filter>*{width:100%}}</style>@endpush
@section('content')
<div class="tax-shell" x-data="{tab:'filing'}" x-cloak>
@if($errors->any())<div class="alert alert-danger mb-0">{{ $errors->first() }}</div>@endif @if(session('success'))<div class="alert alert-success mb-0">{{ session('success') }}</div>@endif
<form class="tax-panel tax-filter" method="get"><div><label class="form-label">เดือนภาษี</label><input class="form-control" type="month" name="period" value="{{ $period }}"></div><div><label class="form-label">สาขา</label><select class="form-select" name="branch_id"><option value="">ทั้งบริษัท</option>@foreach($branches as $branch)<option value="{{ $branch->id }}" @selected($branchId==$branch->id)>{{ $branch->code }} · {{ $branch->name_th }}</option>@endforeach</select></div><button class="btn btn-outline-primary"><i class="bi bi-funnel me-1"></i>แสดง</button></form>
<section class="tax-panel"><div class="tax-tabs"><button class="tax-tab" :class="tab==='filing'&&'active'" @click="tab='filing'" type="button">แบบภาษีรายเดือน</button><button class="tax-tab" :class="tab==='etax'&&'active'" @click="tab='etax'" type="button">E-Tax Invoice</button></div>
<div x-show="tab==='filing'" class="pt-3"><div class="d-flex justify-content-between align-items-start gap-3 flex-wrap mb-3"><div><h2 class="h6 fw-bold mb-1">วงจรจัดทำภาษี</h2><div class="small text-muted">ผู้จัดทำ → ผู้ตรวจคนที่สอง → บันทึกเลขอ้างอิงหลังยื่นจริง</div></div><form method="post" action="{{ route('tax-compliance.filings.prepare') }}" class="d-flex gap-2">@csrf<input type="hidden" name="period" value="{{ $period }}">@if($branchId)<input type="hidden" name="branch_id" value="{{ $branchId }}">@endif<select class="form-select" name="form_type"><option value="PP30">ภ.พ.30</option><option value="PND3">ภ.ง.ด.3</option><option value="PND53">ภ.ง.ด.53</option></select><button class="btn btn-primary text-nowrap"><i class="bi bi-file-earmark-plus me-1"></i>จัดทำชุดใหม่</button></form></div>
<div class="tax-note mb-3"><strong>ขอบเขต:</strong> ไฟล์ CSV เป็น Working paper สำหรับตรวจและนำเข้าระบบสำนักงานบัญชี ไม่ใช่การยื่นกรมสรรพากรอัตโนมัติ ต้องตรวจยอดกับเอกสารและใช้ระบบยื่นที่ได้รับอนุญาต</div>
<div class="table-responsive"><table class="table table-sm"><thead><tr><th>แบบ/เดือน</th><th>สถานะ</th><th class="text-end">ฐานภาษี</th><th class="text-end">ภาษี</th><th>ผู้จัดทำ/ผู้ตรวจ</th><th>SHA-256</th><th>ดำเนินการ</th></tr></thead><tbody>@forelse($filings as $run)<tr><td><strong>{{ $run->form_type }}</strong><div class="text-muted">{{ $run->period }} · {{ $run->branch?->code ?: 'ALL' }} · {{ $run->document_count }} รายการ</div></td><td><span class="badge {{ $run->status==='submitted'?'text-bg-success':($run->status==='reviewed'?'text-bg-primary':'text-bg-warning') }}">{{ $run->status }}</span>@if($run->submission_reference)<div class="small">{{ $run->submission_reference }}</div>@endif</td><td class="text-end">{{ number_format((float)$run->taxable_amount,2) }}</td><td class="text-end fw-bold">{{ number_format((float)$run->tax_amount,2) }}</td><td>{{ $run->preparer?->name }}<div class="text-muted">ตรวจ: {{ $run->reviewer?->name ?: '-' }}</div></td><td><code>{{ substr($run->file_hash,0,14) }}…</code></td><td><div class="tax-actions"><a class="btn btn-sm btn-light border" title="ดาวน์โหลด" href="{{ route('tax-compliance.filings.download',$run) }}"><i class="bi bi-download"></i></a>@if($run->status==='prepared')<form method="post" action="{{ route('tax-compliance.filings.review',$run) }}">@csrf<button class="btn btn-sm btn-outline-primary">ตรวจผ่าน</button></form>@elseif($run->status==='reviewed')<form method="post" action="{{ route('tax-compliance.filings.submit',$run) }}">@csrf<input name="submission_reference" placeholder="เลขอ้างอิงยื่น" required><button class="btn btn-sm btn-success">บันทึกยื่น</button></form>@endif</div></td></tr>@empty<tr><td colspan="7" class="text-center">ยังไม่มีชุดภาษีเดือนนี้</td></tr>@endforelse</tbody></table></div></div>
<div x-show="tab==='etax'" class="pt-3"><div class="d-flex justify-content-between align-items-start gap-3 flex-wrap mb-3"><div><h2 class="h6 fw-bold mb-1">E-Tax Provider Package</h2><div class="small text-muted">สร้าง UUID, payload และ SHA-256 ก่อนส่งผู้ให้บริการ E-Tax ที่บริษัททำสัญญา</div></div><form method="post" action="{{ route('tax-compliance.etax.prepare') }}">@csrf<input type="hidden" name="period" value="{{ $period }}">@if($branchId)<input type="hidden" name="branch_id" value="{{ $branchId }}">@endif<button class="btn btn-primary"><i class="bi bi-filetype-json me-1"></i>เตรียมเอกสารเดือนนี้</button></form></div>
<div class="tax-note mb-3">ระบบยังไม่ส่งตรงกรมสรรพากร เพราะต้องมีใบรับรองอิเล็กทรอนิกส์และบัญชีผู้ให้บริการที่ได้รับอนุมัติ หลังส่งภายนอกให้นำเลขอ้างอิงและผลตอบรับกลับมาบันทึกทุกใบ</div>
<div class="table-responsive"><table class="table table-sm"><thead><tr><th>เอกสาร</th><th>ลูกค้า</th><th>UUID / Hash</th><th>สถานะ</th><th>ผลผู้ให้บริการ</th></tr></thead><tbody>@forelse($etaxDocuments as $etax)<tr><td>{{ $etax->document->doc_number }}<div class="text-muted">{{ $etax->document->doc_date->thaiDate() }} · {{ $etax->document->branch?->code }}</div></td><td>{{ $etax->document->customer?->name_th ?: 'ลูกค้าทั่วไป' }}<div class="text-muted">{{ $etax->document->customer?->tax_id }}</div></td><td><code>{{ $etax->document_uuid }}</code><div><code>{{ substr($etax->payload_hash,0,16) }}…</code></div></td><td><span class="badge {{ $etax->status==='accepted'?'text-bg-success':($etax->status==='rejected'?'text-bg-danger':'text-bg-warning') }}">{{ $etax->status }}</span></td><td><form method="post" action="{{ route('tax-compliance.etax.status',$etax) }}" class="tax-actions">@csrf<select name="status"><option value="sent">ส่งแล้ว</option><option value="accepted">ผ่าน</option><option value="rejected">ไม่ผ่าน</option></select><input name="provider_reference" placeholder="เลขอ้างอิง" required><button class="btn btn-sm btn-outline-primary">บันทึก</button></form></td></tr>@empty<tr><td colspan="5" class="text-center">ยังไม่มี E-Tax package เดือนนี้</td></tr>@endforelse</tbody></table></div></div></section></div>
@endsection
