@extends('layout')
@section('title','Backup และ Security - PopCentral')
@section('page-title','ศูนย์ Backup และ Security')
@section('page-subtitle','ตรวจสำรองข้อมูล ทดสอบกู้คืน MFA Session และเหตุการณ์ความปลอดภัย')
@push('head')<style>.ops-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.ops-stat{padding:14px;background:#fff;border:1px solid var(--erp-border);border-radius:7px}.ops-stat span{display:block;color:var(--erp-muted);font-size:11px;font-weight:800}.ops-stat strong{font-size:21px;color:var(--erp-primary-dark)}.ops-section{margin-top:14px;background:#fff;border:1px solid var(--erp-border);border-radius:7px;padding:14px}.ops-head{display:flex;justify-content:space-between;gap:12px;align-items:center;margin-bottom:10px}.ops-head h2{font-size:15px;font-weight:900;margin:0}.run-log{white-space:pre-wrap;max-width:520px;font-size:10px;color:var(--erp-muted)}@media(max-width:850px){.ops-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:480px){.ops-grid{grid-template-columns:1fr}}</style>@endpush
@section('content')
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif @if(session('error'))<div class="alert alert-danger">{{ session('error') }}</div>@endif
<div class="ops-grid"><div class="ops-stat"><span>ผู้ใช้ Active</span><strong>{{ $security['active_users'] }}</strong></div><div class="ops-stat"><span>เปิด MFA</span><strong>{{ $security['mfa_percent'] }}%</strong></div><div class="ops-stat"><span>รหัสผ่านเกิน 180 วัน</span><strong>{{ $security['stale_passwords'] }}</strong></div><div class="ops-stat"><span>Session 8 ชั่วโมงล่าสุด</span><strong>{{ $security['active_sessions'] }}</strong></div></div>
<section class="ops-section"><div class="ops-head"><div><h2>สำรองและกู้คืนข้อมูล</h2><div class="small text-muted">Backup ถูกบีบอัดและมี SHA-256 ส่วน Restore ด้านล่างตรวจไฟล์เท่านั้น ไม่เขียนทับ Production</div></div><div class="d-flex gap-2"><form method="post" action="{{ route('operations.backup') }}">@csrf<button class="btn btn-primary"><i class="bi bi-database-down me-1"></i>Backup ตอนนี้</button></form><form method="post" action="{{ route('operations.restore-verify') }}">@csrf<button class="btn btn-outline-primary"><i class="bi bi-shield-check me-1"></i>ตรวจ Restore</button></form></div></div><div class="table-responsive"><table class="table table-sm"><thead><tr><th>ไฟล์</th><th>เวลา</th><th>ขนาด</th><th>SHA-256</th></tr></thead><tbody>@forelse($backups as $backup)<tr><td>{{ $backup['name'] }}</td><td>{{ date('d/m/Y H:i',$backup['created_at']) }}</td><td>{{ number_format($backup['size']/1024/1024,2) }} MB</td><td>@if($backup['checksum_status'] === 'ready')<code>{{ $backup['checksum'] }}</code>@elseif($backup['checksum_status'] === 'unreadable')<span class="badge text-bg-danger">อ่าน checksum ไม่ได้</span>@elseif($backup['checksum_status'] === 'invalid')<span class="badge text-bg-warning">checksum ไม่ถูกต้อง</span>@else<span class="text-muted">ไม่มี checksum</span>@endif</td></tr>@empty<tr><td colspan="4" class="text-center">ยังไม่มี Backup</td></tr>@endforelse</tbody></table></div></section>
<section class="ops-section"><div class="ops-head"><div><h2>การยืนยันตัวตน</h2><div class="small text-muted">ผู้ดูแลระบบและฝ่ายการเงินควรเปิด MFA ทุกคน กรณีโทรศัพท์สูญหายให้ผู้ดูแลรีเซ็ตแล้วตั้งใหม่</div></div><a class="btn btn-primary" href="{{ route('mfa.setup') }}"><i class="bi bi-phone me-1"></i>{{ auth()->user()->mfa_enabled_at ? 'จัดการ MFA ของฉัน':'เปิด MFA ของฉัน' }}</a></div>@if($monitorEvents->isNotEmpty())<div class="alert alert-danger"><strong>เหตุการณ์ระบบที่ยังเปิด:</strong> {{ $monitorEvents->pluck('check_code')->implode(', ') }}</div>@endif<div class="table-responsive"><table class="table table-sm"><thead><tr><th>ผู้ใช้</th><th>สาขา</th><th>เข้าใช้ล่าสุด</th><th>MFA</th><th></th></tr></thead><tbody>@foreach($users as $user)<tr><td>{{ $user->name }}<div class="text-muted">{{ $user->username }}</div></td><td>{{ $user->branch?->code ?: 'ส่วนกลาง' }}</td><td>{{ $user->last_login_at?->thaiDate(true) ?: '-' }}</td><td><span class="badge {{ $user->mfa_enabled_at?'text-bg-success':'text-bg-warning' }}">{{ $user->mfa_enabled_at?'เปิด':'ยังไม่เปิด' }}</span></td><td class="text-end">@if($user->mfa_enabled_at)<form method="post" action="{{ route('operations.mfa-reset',$user) }}" onsubmit="return confirm('รีเซ็ต MFA ของผู้ใช้นี้หรือไม่?')">@csrf<input type="hidden" name="confirmation" value="RESET"><button class="btn btn-sm btn-outline-danger" title="รีเซ็ต MFA"><i class="bi bi-phone-x"></i></button></form>@endif</td></tr>@endforeach</tbody></table></div></section>
<section class="ops-section"><div class="ops-head"><h2>ประวัติการทำงานระบบ</h2></div><div class="table-responsive"><table class="table table-sm"><thead><tr><th>เวลา</th><th>งาน</th><th>สถานะ</th><th>ผู้สั่ง</th><th>ผลลัพธ์</th></tr></thead><tbody>@forelse($runs as $run)<tr><td>{{ $run->started_at->thaiDate(true) }}</td><td>{{ $run->operation }}</td><td><span class="badge {{ $run->status==='success'?'text-bg-success':($run->status==='failed'?'text-bg-danger':'text-bg-warning') }}">{{ $run->status }}</span></td><td>{{ $run->runner?->name ?: 'Scheduler' }}</td><td class="run-log">{{ $run->message }}</td></tr>@empty<tr><td colspan="5" class="text-center">ยังไม่มีประวัติ</td></tr>@endforelse</tbody></table></div></section>
<section class="ops-section"><div class="ops-head"><h2>Audit ความปลอดภัยล่าสุด</h2></div><div class="table-responsive"><table class="table table-sm"><thead><tr><th>เวลา</th><th>เหตุการณ์</th><th>ผู้ใช้</th><th>สาขา</th><th>รายละเอียด</th></tr></thead><tbody>@forelse($recentAudits as $audit)<tr><td>{{ $audit->created_at->thaiDate(true) }}</td><td>{{ $audit->action }}</td><td>{{ $audit->user?->name }}</td><td>{{ $audit->branch?->code ?: '-' }}</td><td><code>{{ json_encode($audit->new_values,JSON_UNESCAPED_UNICODE) }}</code></td></tr>@empty<tr><td colspan="5" class="text-center">ยังไม่มีเหตุการณ์</td></tr>@endforelse</tbody></table></div></section>
@endsection
